name: CI build pipeline

on:
  pull_request:
    branches: [ "develop/main" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & Test
        run: xcodebuild clean build test -project 'TikTok Reporter.xcodeproj' -target 'TikTok Reporter' -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0'
