# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Test project"
  lane :tests do
    xcode_select("/Applications/Xcode_15.0.1.app")
    run_tests(project: "TikTok Reporter.xcodeproj",
              devices: ["iPhone 14 (17.0.1)"],
              scheme: "TikTok Reporter")
  end
end
